onlyoffice_main_save:
  path:     /{mode}/save
  defaults: { _controller: OnlyOfficeBundle:OnlyOffice:save }
  requirements: { mode: ".+"}

onlyoffice_main_new:
  path:     /{mode}/new
  defaults: { _controller: OnlyOfficeBundle:OnlyOffice:new }
  requirements: { mode: ".+"}

onlyoffice_main_open:
  path:     /{mode}/open
  defaults: { _controller: OnlyOfficeBundle:OnlyOffice:open }
  requirements: { mode: ".+"}

onlyoffice_main_read:
  path:     /{mode}/read
  defaults: { _controller: OnlyOfficeBundle:OnlyOffice:read }
  requirements: { mode: ".+"}

onlyoffice_main_load:
  path: /load
  defaults: { _controller: OnlyOfficeBundle:OnlyOffice:load }

onlyoffice_main_editor:
  path:     /{mode}
  defaults: { _controller: OnlyOfficeBundle:OnlyOffice:editor }
  requirements: { mode: ".+"}
  methods: [GET]


